language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh
  - git clone --depth=1 https://github.com/lummax/librcimmixcons.git
  - cd librcimmixcons
  - make all CARGO_OPTS=--release
  - sudo make install
  - cd ..

script:
  - mvn compile
  - git diff --exit-code > /dev/null
  - mvn package
  - java -jar target/moco-0.6.jar --help
