language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm build-essential libgc-dev

script:
  - mvn compile
  - git diff --exit-code > /dev/null
  - mvn package
  - java -jar target/moco-0.6.jar --help
